#!/usr/bin/env bash
# Install pre-commit automation:
#   - din-core: native .git/hooks/pre-commit (cargo fmt, clippy, test — matches AGENTS.md)
#   - react-din, din-studio: Husky + .husky/pre-commit (npm test)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

DIN_CORE="${DIN_CORE_PATH:-${DEFAULT_ROOT}/din-core}"
REACT_DIN="${REACT_DIN_PATH:-${DEFAULT_ROOT}/react-din}"
DIN_STUDIO="${DIN_STUDIO_PATH:-${DEFAULT_ROOT}/din-studio}"

install_din_core_hook() {
  local dir="$1"
  if [[ ! -f "${dir}/Cargo.toml" ]]; then
    echo "skip din-core: no Cargo.toml at ${dir}"
    return 0
  fi
  if [[ ! -d "${dir}/.git" ]]; then
    echo "skip din-core: not a git checkout at ${dir}"
    return 0
  fi
  local hook="${dir}/.git/hooks/pre-commit"
  echo "==> din-core (${dir})"
  cat >"${hook}" <<'EOS'
#!/usr/bin/env bash
# Generated by din-agents/scripts/bootstrap-pre-commit-hooks.sh
# Mirrors din-core AGENTS.md quality gates.
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"
cargo fmt --all --check
cargo clippy --workspace --all-targets -- -D warnings
cargo test --workspace
EOS
  chmod +x "${hook}"
  echo "    ${hook} (cargo fmt, clippy, test)"
}

run_in_node_repo() {
  local dir="$1"
  local name="$2"
  if [[ ! -f "${dir}/package.json" ]]; then
    echo "skip ${name}: no package.json at ${dir}"
    return 0
  fi
  if [[ ! -d "${dir}/.git" ]]; then
    echo "skip ${name}: not a git checkout at ${dir}"
    return 0
  fi
  echo "==> ${name} (${dir})"
  (
    cd "${dir}"
    if ! grep -q '"husky"' package.json 2>/dev/null; then
      npm install husky --save-dev
    fi
    if [[ ! -d .husky ]]; then
      npx husky init
    fi
    printf '%s\n' 'npm test' > .husky/pre-commit
    chmod +x .husky/pre-commit
    echo "    .husky/pre-commit -> npm test"
  )
}

install_din_core_hook "${DIN_CORE}"
run_in_node_repo "${REACT_DIN}" "react-din"
run_in_node_repo "${DIN_STUDIO}" "din-studio"

echo ""
echo "Done. Tip: din-core pre-commit runs the full Rust gate suite; it can be slow — use \`git commit --no-verify\` only when intentional."
